server:
  port: 8084
  servlet:
    context-path: /api

spring:
  application:
    name: patient-appointment-system
  
  # Database Configuration (H2 for development, easily switchable to MySQL)
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
    
  # JPA/Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  # H2 Console (for development)
  h2:
    console:
      enabled: true
      path: /h2-console
      
  # Security Configuration
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

# Logging Configuration
logging:
  level:
    com.hospital: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# CORS Configuration
cors:
  allowed-origins: "http://localhost:3000,http://127.0.0.1:5500,http://localhost:5500"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

---
# Production Profile (MySQL)
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:mysql://localhost:3306/patient_appointment_db
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate 